fieldLayouts:
  e70bdf6b-ee40-43cd-a6ba-3e27ae28858f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: Headline
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 81ca1b21-2abf-4ffa-858a-5c5803941ac7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5e03fa67-9a48-43fa-ab59-5b6e7c5f7389 # Excerpt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a39c2386-4a8b-44ed-ad26-f73eb8b8871e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e5415fad-6646-4747-9926-43c065d71f03 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a23e257-2b95-4bd7-af7c-3ec1a9286e31
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4760dfbe-9a94-43c6-ab21-cc97d60acc23
        userCondition: null
handle: news
hasTitleField: true
name: News
section: a52d93b5-142e-408c-97e6-d8092e67edc5 # News
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
