fieldLayouts:
  2717e6f4-be72-4463-adc9-5127e1087c65:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 61593bda-d307-49fe-ae74-ae0611c0858f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 97efe54c-b023-4cd0-ad5e-8aaa31c47c48 # Secondary Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 716423e0-2e9b-48bf-b7f2-d93cf562c161
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 49c330b1-5cbf-47d5-8a1f-eca3a166fdbc
        userCondition: null
fs: images
handle: myImages
name: 'My Images'
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
