columnSuffix: zbpsbfdn
contentColumnType: string(168)
fieldGroup: f210e096-bdd3-40fe-97ef-38538fc7b0a3 # Homepage
handle: heroTitle
instructions: 'Title for Hero Section'
name: 'Hero Title'
searchable: false
settings:
  byteLimit: null
  charLimit: 42
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
