columnSuffix: lrwwyhns
contentColumnType: string(400)
fieldGroup: f210e096-bdd3-40fe-97ef-38538fc7b0a3 # Homepage
handle: heroSupporting
instructions: 'Supporting text'
name: 'Hero Supporting'
searchable: false
settings:
  byteLimit: null
  charLimit: 100
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
