columnSuffix: tjdhyisv
contentColumnType: string(120)
fieldGroup: f210e096-bdd3-40fe-97ef-38538fc7b0a3 # Homepage
handle: secondaryEyebrow
instructions: 'Secondary Text above Headline'
name: 'Secondary Eyebrow'
searchable: false
settings:
  byteLimit: null
  charLimit: 30
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
